FROM techtucson/alpine-php-apache-oci8

RUN mv /var/www/localhost/htdocs/index.php /var/www/localhost/htdocs/info.php

ADD apache/index.html /var/www/localhost/htdocs/index.html
ADD apache/clouds.jpg /var/www/localhost/htdocs/clouds.jpg
