FROM techtucson/alpine-php-apache-oci8

RUN mv /var/www/html/public/index.php /var/www/html/public/info.php

ADD apache/index.html /var/www/html/public/index.html
ADD apache/clouds.jpg /var/www/html/public/clouds.jpg
